### PR TITLE
I fixed the issue

### PR DESCRIPTION
**Pull request by ZILtoid1991**
By commenting out configureMinimumVersion, the binding perfectly works on my side.

### CODE REVIEW

**Comment by mdparker** [comment]
I'm sorry, but removing a feature is not a *fix* for anything. What problem are you trying to solve here?

**Comment by ZILtoid1991** [comment]
The current version of Derelict-util doesn't have that function in that class to be overridden, thus cannot be compiled. Removing that function fixed the issue, I have not seen any issues so far in my application regarding of the Imageformats library.

**Comment by mdparker** [comment]
[configureMinimumVersion](https://github.com/DerelictOrg/DerelictUtil/blob/master/source/derelict/util/loader.d#L303) has been part of DerelictUtil for a while now. I use it regularly with DerelictSDL2. Which version are you referring to?

**Comment by ZILtoid1991** [comment]
Well, it seems I had an earlier version of DerelictUtil.

Feel free to discard my "patch".

**Comment by mdparker** [comment]
Glad you got it sorted.

**Pull request closed without merging**
